#!/bin/bash

# --------------------------------------------------------------------------------
#  kiosk
# --------------------------------------------------------------------------------
#  Raspberry Pi based Kiosks
# 
#  Configuration Script. Allows operator to configure actions of Pi
# --------------------------------------------------------------------------------
#  (C) Copyright Gareth Jones - gareth@gareth.com
# --------------------------------------------------------------------------------
# 

# TODO: create a menu to run one of these
echo "cameras-01-02" > kiosk.config
echo "cameras-03-04" > kiosk.config
echo "cameras-05-06" > kiosk.config
echo "cameras-07-08" > kiosk.config
echo "cameras-09-10" > kiosk.config
echo "cameras-11-12" > kiosk.config
echo "kiosk-01"      > kiosk.config
echo "kiosk-02"      > kiosk.config
echo "kiosk-03"      > kiosk.config
echo "kiosk-04"      > kiosk.config
echo "kiosk-05"      > kiosk.config
echo "kiosk-06"      > kiosk.config
echo "kiosk-07"      > kiosk.config
echo "kiosk-08"      > kiosk.config
echo "kiosk-09"      > kiosk.config
echo "kiosk-10"      > kiosk.config
